=== Yordle38/Projet-Jeu-Vid-o-Trivial-Pursuit/xsd/categorie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/trivialpursuit"
           xmlns:tp="http://www.univ-grenoble-alpes.fr/l3miage/trivialpursuit"
           elementFormDefault="qualified">

    <!-- Déclaration de l'élément racine Categorie -->
    <xs:element name="Categories">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Categorie" type="tp:Categorie" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <xs:unique name="CategorieId">
            <xs:selector xpath="tp:Categorie"/>
            <xs:field xpath="@id"/>
        </xs:unique>
        
        <xs:key name="MesCategoriesKey">
            <xs:selector xpath="tp:Categorie"/>
            <xs:field xpath="@nom"/>
        </xs:key>
        
        <xs:keyref name="CategorieCarte" refer="tp:MesCategoriesKey">
            <xs:selector xpath="tp:Categorie/tp:Cartes/tp:Carte"/>
            <xs:field xpath="@categorie"/>
        </xs:keyref>
    
        <xs:unique name="CarteId">
            <xs:selector xpath="tp:Cartes/tp:Carte"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <!-- Categorie -->
    <xs:complexType name="Categorie">
        <xs:sequence>
            <xs:element name="Cartes" type="tp:Cartes"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="nom" type="tp:MesCategories" use="required"/>
        <xs:attribute name="couleur" type="xs:string" use="required"/>
    </xs:complexType>
    
    
    <xs:simpleType name="MesCategories">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Sport"/>
            <xs:enumeration value="Nature"/>
            <xs:enumeration value="Zythologie"/>
            <xs:enumeration value="Jeux vidéo"/>
            <xs:enumeration value="Histoire"/>
            <xs:enumeration value="Musique"/>
        </xs:restriction>
    </xs:simpleType>

    <!--  Cartes -->
    <xs:complexType name="Cartes">
        <xs:sequence>
            <xs:element name="Carte" type="tp:Carte" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Carte -->
    <xs:complexType name="Carte">
        <xs:sequence>
            <xs:element name="Question" type="xs:string"/>
            <xs:element name="Reponses" type="tp:Reponses">
                <!-- Clé d'unicité pour les identifiants des réponses dans chaque carte -->
                <xs:unique name="ReponseId">
                    <xs:selector xpath="tp:Reponse"/>
                    <xs:field xpath="@id"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="difficulte" type="tp:Difficulte" use="required"/>
        <xs:attribute name="categorie" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Reponses -->
    <xs:complexType name="Reponses">
        <xs:sequence>
            <xs:element name="Reponse" type="tp:Reponse" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Reponse -->
    <xs:complexType name="Reponse">
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="texte" type="xs:string" use="required"/>
        <xs:attribute name="correct" type="xs:boolean" use="required"/>
    </xs:complexType>

    <!--  Difficulte -->
    <xs:simpleType name="Difficulte">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Facile"/>
            <xs:enumeration value="Moyen"/>
            <xs:enumeration value="Difficile"/>
        </xs:restriction>
    </xs:simpleType>



</xs:schema>

=== Yordle38/Projet-Jeu-Vid-o-Trivial-Pursuit/xml/categorie.xml
<?xml version="1.0" encoding="UTF-8"?>
<Categories xmlns="http://www.univ-grenoble-alpes.fr/l3miage/trivialpursuit"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/trivialpursuit ../xsd/categorie.xsd">
    
    
        <!--Zythologie-->   
    <Categorie id="1" nom="Zythologie" couleur="ffcc5c">
    <Cartes>
        <Carte id="101" difficulte="Facile" categorie="Zythologie">
            <Question>Quel est le principal ingrédient de la bière ?</Question>
            <Reponses>
                <Reponse id="1" texte="Orge" correct="true"/>
                <Reponse id="2" texte="Blé" correct="false"/>
                <Reponse id="3" texte="Maïs" correct="false"/>
                <Reponse id="4" texte="Riz" correct="false"/>
            </Reponses>
        </Carte>
        
        <Carte id="102" difficulte="Facile" categorie="Zythologie">
            <Question>Quel est le nom du processus où les levures transforment le sucre en alcool dans la bière ?</Question>
            <Reponses>
                <Reponse id="1" texte="Fermentation" correct="true"/>
                <Reponse id="2" texte="Distillation" correct="false"/>
                <Reponse id="3" texte="Macération" correct="false"/>
                <Reponse id="4" texte="Filtration" correct="false"/>
            </Reponses>
        </Carte>

        <Carte id="103" difficulte="Facile" categorie="Zythologie">
            <Question>Quel type de bière est généralement plus foncé et plus riche en saveur ?</Question>
            <Reponses>
                <Reponse id="1" texte="Stout" correct="true"/>
                <Reponse id="2" texte="Lager" correct="false"/>
                <Reponse id="3" texte="Pilsner" correct="false"/>
                <Reponse id="4" texte="Blonde" correct="false"/>
            </Reponses>
        </Carte>

        <Carte id="104" difficulte="Facile" categorie="Zythologie">
            <Question>Quel pays est célèbre pour ses bières trappistes ?</Question>
            <Reponses>
                <Reponse id="1" texte="Belgique" correct="true"/>
                <Reponse id="2" texte="Allemagne" correct="false"/>
                <Reponse id="3" texte="République " correct="false"/>
                <Reponse id="4" texte="Tchèque" correct="false"/>
                <Reponse id="5" texte="Pays-Bas" correct="false"/>
            </Reponses>
        </Carte>

        <Carte id="105" difficulte="Moyen" categorie="Zythologie">
            <Question>Quel type de levure est utilisé pour les bières de type ale ?</Question>
            <Reponses>
                <Reponse id="1" texte="Levure haute" correct="true"/>
                <Reponse id="2" texte="Levure basse" correct="false"/>
                <Reponse id="3" texte="Levure sauvage " correct="false"/>
                <Reponse id="4" texte="Levure sèche" correct="false"/>
            </Reponses>
        </Carte>

        <Carte id="106" difficulte="Moyen" categorie="Zythologie">
            <Question>Quel est le nom du récipient utilisé pour la fermentation de la bière ?</Question>
            <Reponses>
                <Reponse id="1" texte="Cuve de fermentation" correct="true"/>
                <Reponse id="2" texte="Alambic" correct="false"/>
                <Reponse id="3" texte="Fût" correct="false"/>
                <Reponse id="4" texte="Tonneau" correct="false"/>
            </Reponses>
        </Carte>

        <Carte id="107" difficulte="Moyen" categorie="Zythologie">
            <Question>Quel type de bière est souvent associé à la ville de Munich ?</Question>
            <Reponses>
                <Reponse id="1" texte="Weizen" correct="true"/>
                <Reponse id="2" texte="Porter" correct="false"/>
                <Reponse id="3" texte="IPA" correct="false"/>
                <Reponse id="4" texte="Lambic" correct="false"/>
            </Reponses>
        </Carte>

        <Carte id="108" difficulte="Moyen" categorie="Zythologie">
            <Question>Quel est le nom du processus qui consiste à ajouter du houblon à la bière ?</Question>
            <Reponses>
                <Reponse id="1" texte="Houblonnage" correct="true"/>
                <Reponse id="2" texte="Maltage" correct="false"/>
                <Reponse id="3" texte="Brassage" correct="false"/>
                <Reponse id="4" texte="Filtration" correct="false"/>
            </Reponses>
        </Carte>
        
        <Carte id="109" difficulte="Difficile" categorie="Zythologie">
            <Question>Quel est le nom du composé chimique responsable de l'amertume dans la bière ?</Question>
            <Reponses>
                <Reponse id="1" texte="Lupuline" correct="true"/>
                <Reponse id="2" texte="Maltose" correct="false"/>
                <Reponse id="3" texte="Dextrine" correct="false"/>
                <Reponse id="4" texte="Isomérisation" correct="false"/>
            </Reponses>
        </Carte>

        <Carte id="110" difficulte="Difficile" categorie="Zythologie">
            <Question>Quel type de bière est traditionnellement brassé avec des fruits ?</Question>
            <Reponses>
                <Reponse id="1" texte="Lambic" correct="true"/>
                <Reponse id="2" texte="Pilsner" correct="false"/>
                <Reponse id="3" texte="Stout" correct="false"/>
                <Reponse id="4" texte="Lager" correct="false"/>
            </Reponses>
        </Carte>

        <Carte id="111" difficulte="Difficile" categorie="Zythologie">
            <Question>Quel est le nom du processus de vieillissement de la bière en fût de chêne ?</Question>
            <Reponses>
                <Reponse id="1" texte="Vieillissement en fût" correct="true"/>
                <Reponse id="2" texte="Carbonatation" correct="false"/>
                <Reponse id="3" texte="Pasteurisation" correct="false"/>
                <Reponse id="4" texte="Clarification" correct="false"/>
            </Reponses>
        </Carte>

        <Carte id="112" difficulte="Difficile" categorie="Zythologie">
            <Question>Quel est le nom de la bière traditionnelle japonaise ?</Question>
            <Reponses>
                <Reponse id="1" texte="Sake" correct="true"/>
                <Reponse id="2" texte="Asahi" correct="false"/>
                <Reponse id="3" texte="Kirin" correct="false"/>
                <Reponse id="4" texte="Sapporo" correct="false"/>
            </Reponses>
        </Carte>
    </Cartes>
</Categorie>



    <!--Histoire-->
    <Categorie id="2" nom="Histoire" couleur="b2ebf2">
        <Cartes>
            <Carte id="101" difficulte="Facile" categorie="Histoire">
                <Question>Qui a découvert l'Amérique en 1492 ?</Question>
                <Reponses>
                    <Reponse id="1" texte="Christophe Colomb" correct="true"/>
                    <Reponse id="2" texte="Amerigo Vespucci" correct="false"/>
                    <Reponse id="3" texte="Ferdinand Magellan" correct="false"/>
                    <Reponse id="4" texte="Vasco de Gama" correct="false"/>
                </Reponses>
            </Carte>

            <Carte id="102" difficulte="Facile" categorie="Histoire">
                <Question>Quel était le nom du premier président des États-Unis ?</Question>
                <Reponses>
                    <Reponse id="1" texte="George Washington" correct="true"/>
                    <Reponse id="2" texte="Thomas Jefferson" correct="false"/>
                    <Reponse id="3" texte="John Adams" correct="false"/>
                    <Reponse id="4" texte="James Madison" correct="false"/>
                </Reponses>
            </Carte>

            <Carte id="105" difficulte="Moyen" categorie="Histoire">
                <Question>Quel traité a mis fin à la Première Guerre mondiale ?</Question>
                <Reponses>
                    <Reponse id="1" texte="Traité de Versailles" correct="true"/>
                    <Reponse id="2" texte="Traité de Trianon" correct="false"/>
                    <Reponse id="3" texte="Traité de Sèvres" correct="false"/>
                    <Reponse id="4" texte="Traité de Saint-Germain" correct="false"/>
                </Reponses>
            </Carte>

            <Carte id="106" difficulte="Moyen" categorie="Histoire">
                <Question>Qui était le leader de la révolution cubaine en 1959 ?</Question>
                <Reponses>
                    <Reponse id="1" texte="Fidel Castro" correct="true"/>
                    <Reponse id="2" texte="Che Guevara" correct="false"/>
                    <Reponse id="3" texte="Raúl Castro" correct="false"/>
                    <Reponse id="4" texte="Camilo Cienfuegos" correct="false"/>
                </Reponses>
            </Carte>

            <Carte id="107" difficulte="Moyen" categorie="Histoire">
                <Question>Quel était le nom du premier empereur de Chine ?</Question>
                <Reponses>
                    <Reponse id="1" texte="Qin Shi Huang" correct="true"/>
                    <Reponse id="2" texte="Sun Yat-sen" correct="false"/>
                    <Reponse id="3" texte="Kangxi" correct="false"/>
                    <Reponse id="4" texte="Mao Zedong" correct="false"/>
                </Reponses>
            </Carte>

            <Carte id="108" difficulte="Moyen" categorie="Histoire">
                <Question>En quelle année a eu lieu la bataille de Waterloo ?</Question>
                <Reponses>
                    <Reponse id="1" texte="1815" correct="true"/>
                    <Reponse id="2" texte="1805" correct="false"/>
                    <Reponse id="3" texte="1812" correct="false"/>
                    <Reponse id="4" texte="1820" correct="false"/>
                </Reponses>
            </Carte>

            <Carte id="109" difficulte="Difficile" categorie="Histoire">
