=== Yordle38/Projet-Jeu-Vid-o-Trivial-Pursuit/xsd/game.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/trivialpursuit"
    xmlns:tp="http://www.univ-grenoble-alpes.fr/l3miage/trivialpursuit"
    elementFormDefault="qualified">
    
    <!-- Element racine -->
    <xs:element name="TrivialPursuit" type="tp:TrivialPursuit">
        <xs:unique name="CategorieId">
            <xs:selector xpath="tp:Categories/tp:Categorie"/>
            <xs:field xpath="@id"/>
        </xs:unique>
        
        <xs:unique name="JoueurId">
            <xs:selector xpath="tp:Joueurs/tp:Joueur"/>
            <xs:field xpath="@id"/>
        </xs:unique>

        <xs:unique name="CasePosition">
            <xs:selector xpath="tp:Plateau/tp:Cases/tp:Case"/>
            <xs:field xpath="tp:Sprite/@positionX"/>
            <xs:field xpath="tp:Sprite/@positionY"/>
        </xs:unique>

        <xs:unique name="ReponseID">
            <xs:selector xpath="tp:Carte/tp:Question/tp:Reponse"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    

        <xs:unique name="CarteId">
            <xs:selector xpath="tp:Categories/tp:Categorie/tp:Cartes/tp:Carte"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>
    
        <xs:complexType name="TrivialPursuit">
            <xs:sequence>
                <xs:element name="Plateau" type="tp:Plateau"/>
                <xs:element name="Categories">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Categorie" type="tp:Categorie" maxOccurs="unbounded"/> 
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Joueurs">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Joueur" type="tp:Joueur" maxOccurs="unbounded"/>
                        </xs:sequence> 
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    
    <!-- Plateau -->
   <xs:complexType name="Plateau">
       <xs:sequence>
           <xs:element name="Cases">
               <xs:complexType>
                   <xs:sequence>
                       <xs:element name="Case" type="tp:Case" maxOccurs="unbounded"/>
                   </xs:sequence>
               </xs:complexType>
           </xs:element>
           <xs:element name="Background">
               <xs:complexType>
                   <xs:attribute name="texture" type="xs:string" use="required"/>
               </xs:complexType>
           </xs:element>        
       </xs:sequence>
   </xs:complexType>


    
    <!-- Case -->
    <xs:complexType name="Case">
        <xs:sequence>
            <xs:element name="Joker" type="tp:Joker" minOccurs="0"/>
            <xs:element name="Sprite" type="tp:Sprite"/>
        </xs:sequence>
        
        <!--<xs:attribute name="id" type="xs:int" use="optional"/> -->
        <xs:attribute name="couleur" type="tp:Couleur" use="required"/>
        <xs:attribute name="type" type="tp:TYPECASE" use="required"/>
    </xs:complexType>
    
    <!-- types de cases-->
    <xs:simpleType name="TYPECASE">
        <xs:restriction base="xs:string">
            <xs:enumeration value="VIDE"/>
            <xs:enumeration value="QUESTION"/>
            <xs:enumeration value="CHANCE"/>
            <xs:enumeration value="CHALLENGE"/>
            <xs:enumeration value="JOKER"/>
        </xs:restriction>
    </xs:simpleType>
    

    
    
    <!-- Sprite -->
    <xs:complexType name="Sprite">
            <xs:attribute name="texture" type="xs:string" use="required"/>
            <xs:attribute name="couleur" type="tp:Couleur" use="required"/>
            <xs:attribute name="positionX" type="xs:int" use="required"/>
            <xs:attribute name="positionY" type="xs:int" use="required"/>
            <xs:attribute name="size" type="xs:int" use="required"/>
            <xs:attribute name="sizeMin" type="xs:int" use="required"/>
    </xs:complexType>

    <xs:simpleType name="Couleur">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BLEU"/>
            <xs:enumeration value="ROUGE"/>
            <xs:enumeration value="JAUNE"/>
            <xs:enumeration value="VERT"/>
            <xs:enumeration value="ORANGE"/>
            <xs:enumeration value="ROSE"/>
            <xs:enumeration value="GRIS"/>
        </xs:restriction>
    </xs:simpleType>



    <xs:simpleType name="Difficulte">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Facile"/>
            <xs:enumeration value="Moyen"/>
            <xs:enumeration value="Difficile"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    <!-- Joker -->
    <xs:complexType name="Joker">
            <xs:attribute name="id" type="xs:int" use="required"/>
            <xs:attribute name="nom" type="xs:string" use="required"/>
            <xs:attribute name="effet" type="xs:string" use="required"/>
    </xs:complexType>


    <!-- Categorie  -->
    <xs:complexType name="Categorie">
        <xs:sequence>
            <xs:element name="Cartes">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Carte" type="tp:Carte" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element> 
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="nom" type="xs:string" use="required"/>
        <xs:attribute name="couleur" type="tp:Couleur" use="required"/>
    </xs:complexType>

    <!-- Carte  -->
    <xs:complexType name="Carte">
        <xs:sequence>
            <xs:element name="Question" type="xs:string"/>
            <xs:element name="Reponses">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Reponse" type="tp:Reponse" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>        
        </xs:sequence> 
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="difficulte" type="tp:Difficulte" use="required"/>
    </xs:complexType>

    <xs:complexType name="Reponses">
        <xs:sequence>
            <xs:element name="Reponse" type="Reponse" maxOccurs="unbounded"/>
        </xs:sequence> 
    </xs:complexType>
    

    <!-- Reponse  -->
    <xs:complexType name="Reponse">
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="texte" type="xs:string" use="required"/>
        <xs:attribute name="correct" type="xs:boolean" use="required"/>
    </xs:complexType>

    <!-- Joueur  -->
    <xs:complexType name="Joueur">
        <xs:sequence>
            <xs:element name="Pion">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attribute name="imageLink" type="xs:string" use="required"/>
                    <xs:attribute name="description" type="xs:string" use="required"/>
                    <xs:attribute name="case" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="Jokers">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Joker" type="tp:Joker" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="nom" type="xs:string" use="required"/>
        <xs:attribute name="score" type="xs:int" use="required"/>
    </xs:complexType>


    <!-- Pion du joueur  -->
    <xs:complexType name="Pion">
        <xs:attribute name="nom" type="xs:string" use="required"/>
        <xs:attribute name="imageLink" type="xs:string" use="required"/>
        <xs:attribute name="description" type="xs:string" use="required"/>
        <xs:attribute name="case" type="Case" use="required"/>
    </xs:complexType>
    
</xs:schema>

=== Yordle38/Projet-Jeu-Vid-o-Trivial-Pursuit/xml/game.xml
<?xml version="1.0" encoding="UTF-8"?>
<TrivialPursuit xmlns="http://www.univ-grenoble-alpes.fr/l3miage/trivialpursuit"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/trivialpursuit ../xsd/game.xsd">
    <Plateau>
        <Cases>
            <Case  couleur="BLEU" type="VIDE" >
                <Sprite texture="case1_texture.png" couleur="BLEU" positionX="10" positionY="10" size="20" sizeMin="20"/>
            </Case>

            
            
            <Case couleur="ROUGE" type="QUESTION" >
                    <Sprite texture="case2_texture.png" couleur="ROUGE" positionX="10" positionY="15" size="25" sizeMin="15"/>
            </Case>

            <Case  couleur="VERT" type="CHANCE" >
                <Sprite texture="case2_texture.png" couleur="VERT" positionX="20" positionY="10" size="25" sizeMin="15"/>
            </Case>
            
            <Case  couleur="ORANGE" type="CHALLENGE"  >
                <Sprite texture="case2_texture.png" couleur="ORANGE" positionX="25" positionY="10" size="25" sizeMin="15"/>
            </Case>
        </Cases>
        <Background texture="plateau_texture.png"/>
    </Plateau>
    
    
    <Categories>
        <Categorie id="1" nom="Histoire" couleur="ROUGE">
            <Cartes>
                <Carte id="101" difficulte="Facile">
                    <Question> Le premier président de la france ?</Question>
                    <Reponses>
                        <Reponse id="1" texte="Louis-Napoléon Bonaparte" correct="true"/>
                        <Reponse id="2" texte="Gaston Doumergue" correct="false"/>
                    </Reponses>
                </Carte>
                <Carte id="102" difficulte="Moyen">
                    <Question> Quelle année la seconde guerre mondiale a t elle pris fin ? </Question>
                    <Reponses>
                        <Reponse id="1" texte="1945" correct="true"/>
                        <Reponse id="2" texte="1938" correct="false"/>
                        <Reponse id="3" texte="1952" correct="false"/>
                        <Reponse id="4" texte="1920" correct="false"/>
                    </Reponses>
                </Carte>
            </Cartes>
        </Categorie>

        
        <Categorie id="2" nom="Science" couleur="VERT">
            <Cartes>
                <Carte id="201" difficulte="Difficile">
                    <Question> quelle est la formule chimique de l'eau ?</Question>
                    <Reponses>
                        <Reponse id="1" texte="H2O" correct="true"/>
                        <Reponse id="2" texte="CO2" correct="false"/>
                        <Reponse id="3" texte="O2" correct="false"/>
                        <Reponse id="4" texte="H2O2" correct="false"/>
                    </Reponses>
                </Carte>
            </Cartes>
        </Categorie>
    </Categories>
    
    
    
    <Joueurs>
        <Joueur id="1" nom="Bob" score="4">
            <Pion name="pion1" imageLink="pion1.png" description="pion bleu" case="1"/>
            <Jokers>
                <Joker id="1" nom="50/50" effet="Supprimer deux mauvaises réponses"/>
            </Jokers>
        </Joueur>
        <Joueur id="2" nom="Toto" score="2">
            <Pion name="Pion2" imageLink="pion2.png" description="Pion rouge" case="5"/>
            <Jokers>
                <Joker id="2" nom="Relance de question" effet="Permet de relancer la question"/>
            </Jokers>
        </Joueur>
    </Joueurs>
</TrivialPursuit>

=== Yordle38/Projet-Jeu-Vid-o-Trivial-Pursuit/xml/trivialpursuit.xml
<?xml version="1.0" encoding="utf-8"?>
<TrivialPursuit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/trivialpursuit ../xsd/game.xsd" xmlns="http://www.univ-grenoble-alpes.fr/l3miage/trivialpursuit">
  <Plateau>
    <Cases>
      <Case type="VIDE" couleur="BLEU">
        <Sprite texture="a" positionX="7" positionY="10" size="20" sizeMin="4" couleur="BLEU" />
      </Case>
      <Case type="VIDE" couleur="BLEU">
        <Sprite texture="case1_texture.png" positionX="13" positionY="10" size="20" sizeMin="4" couleur="BLEU" />
      </Case>
      <Case type="QUESTION" couleur="ROUGE">
        <Sprite texture="case2_texture.png" positionX="10" positionY="15" size="25" sizeMin="4" couleur="BLEU" />
      </Case>
    </Cases>
    <Background texture="plateau_texture.png" />
  </Plateau>
  <Categories>
    <Categorie id="1" nom="Histoire" couleur="ROUGE">
      <Cartes>
        <Carte id="101" difficulte="Facile">
          <Question>Le premier président de la France ?</Question>
          <Reponses>
            <Reponse id="1" texte="Louis-Napoléon Bonaparte" correct="true" />
            <Reponse id="2" texte="Gaston Doumergue" correct="false" />
          </Reponses>
        </Carte>
      </Cartes>
    </Categorie>
  </Categories>
  <Joueurs>
    <Joueur id="1" nom="Bob" score="4">
      <Pion name="pion1" imageLink="pion1.png" description="pion bleu" case="1" />
      <Jokers>
        <Joker id="1" nom="50/50" effet="Supprimer deux mauvaises réponses" />
      </Jokers>
    </Joueur>
  </Joueurs>
</TrivialPursuit>
